version: '3'
services:
  web:
    build: .
    command: >
      gunicorn -w4 -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './web_app:/web_app'
    ports:
      - '8000:8000'
  nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
    volumes:
        - /www/static
    links:
        - web:web
